"""
Data schemas for the QR scan service.

These classes describe exactly what data the API accepts and returns.
FastAPI uses them to:
  * check incoming data automatically (wrong type or missing field -> HTTP 422 error)
  * convert JSON into Python objects
  * generate the interactive documentation at /docs
"""

from datetime import datetime
from enum import Enum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, Field, model_validator


# ---------------------------------------------------------------------------
# Enums: fields that may only take a fixed set of values
# ---------------------------------------------------------------------------

class Platform(str, Enum):
    IOS = "ios"
    ANDROID = "android"


class DecoderType(str, Enum):
    """Which component produced the decoded text on the phone."""
    ZXING = "zxing"
    OPENCV = "opencv"
    ML_MODEL = "ml_model"
    NONE = "none"  # nothing could decode the image


class OutcomeMethod(str, Enum):
    """How the driver finally found (or did not find) the charger."""
    QR = "qr"                        # the scan itself worked
    MANUAL_ENTRY = "manual_entry"    # driver typed the ID printed on the sticker
    MAP_SELECTION = "map_selection"  # driver picked the charger from the map/list
    ABANDONED = "abandoned"          # driver gave up


# ---------------------------------------------------------------------------
# Building blocks: small groups of related fields
# ---------------------------------------------------------------------------

class DeviceInfo(BaseModel):
    """Which phone and app version made the scan."""
    platform: Platform
    device_model: str = Field(..., max_length=100, examples=["iPhone 15"])
    os_version: str = Field(..., max_length=50, examples=["17.5"])
    app_version: str = Field(..., max_length=50, examples=["4.12.0"])


class CameraInfo(BaseModel):
    """Camera settings at the moment the image was taken.

    Most fields are optional because not every phone reports them.
    """
    image_width: int = Field(..., gt=0, description="Width in pixels")
    image_height: int = Field(..., gt=0, description="Height in pixels")
    is_cropped: bool = Field(False, description="True if the app sends only the QR region")
    exposure_time_ms: float | None = Field(None, gt=0)
    iso: int | None = Field(None, gt=0)
    focus_distance_m: float | None = Field(None, ge=0)
    torch_on: bool = False
    ambient_lux: float | None = Field(None, ge=0, description="Light sensor reading")


class Location(BaseModel):
    """GPS position of the driver, used to narrow down nearby chargers."""
    latitude: float = Field(..., ge=-90, le=90)
    longitude: float = Field(..., ge=-180, le=180)
    accuracy_m: float | None = Field(None, ge=0, description="GPS accuracy radius in metres")


class DecodeResult(BaseModel):
    """What the phone managed to read from the image."""
    success: bool
    decoded_text: str | None = Field(None, max_length=2048)
    decoder: DecoderType = DecoderType.NONE
    attempts: int = Field(1, ge=1, description="Frames tried before giving up or succeeding")
    duration_ms: int = Field(..., ge=0, description="Time from camera open to result")

    @model_validator(mode="after")
    def check_consistency(self) -> "DecodeResult":
        if self.success and not self.decoded_text:
            raise ValueError("decoded_text is required when success is true")
        if self.success and self.decoder == DecoderType.NONE:
            raise ValueError("decoder cannot be 'none' when success is true")
        return self


# ---------------------------------------------------------------------------
# Request and response bodies for the endpoints
# ---------------------------------------------------------------------------

class ScanCreate(BaseModel):
    """Metadata sent with every scan to POST /v1/scans.

    The image itself is sent as a separate file in the same multipart request.
    """
    scan_id: UUID = Field(..., description="Generated by the app; lets the server ignore duplicate retries")
    session_id: UUID = Field(..., description="Groups several scan attempts by one driver")
    captured_at: AwareDatetime = Field(..., description="Must include a timezone, e.g. 2026-10-06T14:00:00+02:00")
    device: DeviceInfo
    camera: CameraInfo
    location: Location | None = Field(None, description="None if the driver denied location access")
    decode: DecodeResult
    consent_for_training: bool = Field(..., description="Driver agreed that this image may be used for training (GDPR)")


class ScanCreatedResponse(BaseModel):
    """Returned by POST /v1/scans."""
    scan_id: UUID
    received_at: datetime
    status: str = "stored"


class OutcomeUpdate(BaseModel):
    """Sent to PATCH /v1/scans/{scan_id}/outcome once the driver found a charger.

    This is what turns a scan into a labelled training example.
    """
    method: OutcomeMethod
    charger_id: str | None = Field(None, max_length=100, description="Internal charger ID that was finally used")
    evse_id: str | None = Field(None, max_length=100, examples=["NL*TNM*E12345*1"])
    resolved_at: AwareDatetime

    @model_validator(mode="after")
    def check_charger_present(self) -> "OutcomeUpdate":
        if self.method == OutcomeMethod.ABANDONED and self.charger_id is not None:
            raise ValueError("charger_id must be empty when method is 'abandoned'")
        if self.method != OutcomeMethod.ABANDONED and self.charger_id is None:
            raise ValueError("charger_id is required unless method is 'abandoned'")
        return self


class OutcomeResponse(BaseModel):
    """Returned by PATCH /v1/scans/{scan_id}/outcome."""
    scan_id: UUID
    labelled: bool = Field(..., description="True if this scan can now be used for training")


class PredictionResponse(BaseModel):
    """Returned by POST /v1/predict."""
    text: str = Field(..., examples=["NL*TNM*E12345*1"])
    confidence: float = Field(..., ge=0, le=1, description="How sure the model is (0-1)")
    model_version: str


class ChargerSuggestion(BaseModel):
    charger_id: str
    evse_id: str
    score: float = Field(..., ge=0, le=1, description="Similarity between what was read and this charger's ID")


class ImageQualityOut(BaseModel):
    brightness: float
    contrast: float
    sharpness: float
    is_dark: bool
    is_overexposed: bool
    is_low_contrast: bool
    is_blurry: bool


class ResolveResponse(BaseModel):
    """Returned by POST /v1/resolve.

    The app decides what to show from `status`:
      matched    -> start charging at `charger_id`
      candidates -> "Is it one of these?" with `candidates`
      not_found  -> show `hints` and the manual entry field
    """
    status: str = Field(..., examples=["matched"])
    stage: str = Field(..., description="Which step found the answer: qr_raw, qr_<enhancement>, ocr or none")
    charger_id: str | None = None
    evse_id: str | None = None
    candidates: list[ChargerSuggestion] = []
    read_text: str | None = Field(None, description="What the QR decoder or the model read")
    ocr_confidence: float | None = None
    model_version: str | None = None
    hints: list[str] = Field([], description="Tips to show the driver, e.g. 'Turn on the flashlight'")
    quality: ImageQualityOut
    duration_ms: float
